export default function(){
return {
    "pie_graph":{
        id: "pie_graph",
        param: {
            "type": "pie",
            "fontFamily": "'Open Sans', sans-serif",
            //"startAngle": 10,
            "categoryField": "category",
            "balloonText":"[[category]]:<br>[[val]] млрд. руб",
            "thousandsSeparator": " ",
            "startDuration":0,
            "outlineThickness":1,
            "outlineAlpha":1,
            "outlineColor":"#36414d",
            "sequencedAnimation":false,
            "percentPrecision":0,
            "labelText": "[[val]]",
            // "labelsEnabled": false,
            "titleField": "category",
            "valueField": "val",
            "allLabels": [],
            "color":"#a1abb8",
            "innerRadius":"70%",
            "fontSize":13,
            "balloon": {},
            "pullOutRadius": "0%",
            "startRadius": "50%",
            //"autoMargins": false,
            // "marginBottom":10,
            // "marginRight":10,
            // "marginLeft":10,
            // "marginTop":10,
            "labelTickAlpha": 0.2,
            "labelTickColor": "#a1abb8",
            "labelRadius": 10,
            "titles": [],
            "colors":  [
                "#61DB96",
                "#F5A623",
                "#6EC7F7",
                "#2ACED0",
                "#8064a2",
                "#a76eff",
                "#64A7D2",
                "#04D215",
                "#0D52D1",
                "#2A0CD0",
                "#8A0CCF",
                "#CD0D74"] ,
            "dataProvider": [
                {"category": "Валютные договоры","val": "15"},
                {"category": "Объекты ЦА","val": "3"},
                {"category": "Переформатированные ВСП","val": "7"},
                {"category": "Коммерческие помещения","val": "8"},
                {"category": "Муниципальные помещения","val": "5"}
            ]
        },
        test: "inner_test"
    },
    "pie_graph_sec":{
        id: "pie_graph_sec",
        param: {
            "type": "pie",
            "fontFamily": "'Open Sans', sans-serif",
            //"startAngle": 10,
            "categoryField": "category",
            "balloonText":"[[category]]:<br>[[val]] млрд. руб",
            "thousandsSeparator": " ",
            "startDuration":0,
            "outlineThickness":1,
            "outlineAlpha":1,
            "outlineColor":"#36414d",
            "sequencedAnimation":false,
            "percentPrecision":0,
            "labelText": "[[val]]",
            // "labelsEnabled": false,
            "titleField": "category",
            "valueField": "val",
            "allLabels": [],
            "color":"#a1abb8",
            "innerRadius":"70%",
            "fontSize":13,
            "balloon": {},
            "pullOutRadius": "0%",
            "startRadius": "50%",
            //"autoMargins": false,
            // "marginBottom":10,
            // "marginRight":10,
            // "marginLeft":10,
            // "marginTop":10,
            "labelTickAlpha": 0.2,
            "labelTickColor": "#a1abb8",
            "labelRadius": 10,
            "titles": [],
            "colors":  [
                "#61DB96",
                "#F5A623",
                "#6EC7F7",
                "#2ACED0",
                "#8064a2",
                "#a76eff",
                "#64A7D2",
                "#04D215",
                "#0D52D1",
                "#2A0CD0",
                "#8A0CCF",
                "#CD0D74"] ,
            "dataProvider": [
                {"category": "Валютные договоры","val": "15"},
                {"category": "Объекты ЦА","val": "12"}
            ]
        },
        test: "inner_test"
    },
    "test":"test_string"
}
}
